# global
glob: data/A.fasta.gz
seed: 7080
min_unk: 0.01
max_dup: 3
# IQ-TREE v2.0.3
ufboot: 1000
ufjack: 1000
# Gubbins v2.4.1
tree_builder: fasttree
iterations: 10
filter_percentage: 100
# BactDating v1.1
reps: 1
models:
  - poisson
  - negbin
  - strictgamma
  - relaxedgamma
  - mixedgamma
  - arc
  - carc
  - mixedcarc
nbIts: 1000
thin: 100
burn: 0.50
ess: 200
